### ISSUE TITLE
materiaaklasse: vraag bij ct:

### ISSUE THREAD

**Issue by ChandraAlgoe** [bodemenondergrond/codelijst-materiaalklasse#1]
In de DOV-codetabel materiaalklasse staat et ct:lucht en ct:water. Moet dit niet gewoon Lucht en Water zijn?

![image](https://github.com/bodemenondergrond/codelijst-materiaalklasse/assets/48786550/2d4571d1-4eed-4433-a25c-1b5f67ed2195)

**Comment by debaetpa** [comment]
ja, het prevLabel voor die 2 is foutief
