### ISSUE TITLE
Publicatie V0.2

### ISSUE THREAD

**Issue by dluts** [bodemenondergrond/codelijst-materiaalklasse#2]
De prerelease 0.2 van de codelijst materiaalklasse is goedgekeurd voor de publicatie (door OC DOV op 09/07/2024). 
In de attachment vind je versie 0.2 van deze codelijst met de toevoeging van 1 nieuwe code, 'eluaat', ten opzichte van de huidige codelijst.

[codelijst_source.xlsx](https://github.com/user-attachments/files/16163226/codelijst_source.xlsx)

Omdat dit een prerelease is, specifiek om te beantwoorden aan noden die zijn opgedoken met nieuwe data die aan DOV  toegevoegd worden, is het niet meteen de bedoeling om deze al te publiceren via data.bodemenondergrond.vlaanderen.be

**Comment by dluts** [comment]
**Verantwoording:**

- Het hoofddoel van deze release is om vanwege een urgente nood snel een code toe te voegen voor het capteren van de materiaalklasse van monsters bekomen door een uitlogingsproef.
- Deze release is een pre-release voor v1 van de codelijst, om snel te schakelen is er niet in detail ingegeaan op de overige codes en zijn de definities voor de codes niet vastgelegd.
- Bij een uitlogingsproef wordt er uit een vast monster (bodem, vaste deel van de aarde, ....) een vloeibaar staal genomen. Omdat het staal, dat genomen wordt uit het originele monster, een andere fase heeft (vloeibaar ipv vast) heeft, heeft het ook een andere materiaalklasse dan het originele monster. Omdat we met de code specifiek een vloeistof bedoelen die het resultaat is van de uitloging van een monster met materiaalklasse van het vaste deel van de aarde, is er gekozen om een nieuwe code 'eluaat' toe te voegen en deze, terwijl het een vloeistof is, in de hiërarchie te plaatsen onder 'Vaste deel van de aarde'.
- In principe kan 'eluaat' ook bekomen worden uit afval. Afval wordt op dit moment niet gecapteerd door de bodem en ondergrond materiaalklasse codelijst. Nog na te vragen bij een linked data specialist: We gaan er nu vanuit dat bij het toevoegen van bijvoorbeeld afval aan de codelijst, het mogelijk is om in de hiërarchie zowel 'vaste deel van de aarde' als 'afval' als bovenliggend object te hebben via 'broader'.

**Voor een volgende versie:**

- Het toevoegen van de definities bij alle materiaalklasse codes.
- Uitklaren hoe eluaat correct aan zowel 'afval' als 'vaste deel van de aarde' kan gelinkt worden.

**Comment by debaetpa** [comment]
v0.2.0 released
